version: '3'
services:
  generator:
    build: .
    volumes:
      - ./data:/data
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./data:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
